//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//


using System;
using HalconDotNet;
using VisionPlatform.BaseType;



namespace AgvLocate
{
    public partial class VisionOperation
    {
        // Chapter: Graphics / Text
        // Short Description: This procedure writes a text message. 
        public void disp_message(HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem,
            HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
        {
            throw new Exception();
        }



    }
}
