//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//


using System;
using HalconDotNet;



namespace AgvLocate
{
    public partial class VisionOperation
    {
        // Chapter: XLD / Creation
        // Short Description: Creates an arrow shaped XLD contour. 
        public void gen_arrow_contour_xld(out HObject ho_Arrow, HTuple hv_Row1, HTuple hv_Column1,
            HTuple hv_Row2, HTuple hv_Column2, HTuple hv_HeadLength, HTuple hv_HeadWidth)
        {
            throw new Exception();
        }

    }
}
