//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//


using System;
using HalconDotNet;



namespace AgvLocate
{

    public partial class VisionOperation
    {
        public void pts_to_best_circle(out HObject ho_Circle, HTuple hv_Rows, HTuple hv_Cols,
            HTuple hv_ActiveNum, HTuple hv_ArcType, out HTuple hv_RowCenter, out HTuple hv_ColCenter,
            out HTuple hv_Radius, out HTuple hv_StartPhi, out HTuple hv_EndPhi, out HTuple hv_PointOrder,
            out HTuple hv_ArcAngle)
        {
            throw new Exception();
        }



    }
}
