//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//


using System;
using HalconDotNet;

namespace AgvLocate
{

    public partial class VisionOperation
    {
        public void spoke(HObject ho_Image, out HObject ho_Regions, HTuple hv_Elements,
            HTuple hv_DetectHeight, HTuple hv_DetectWidth, HTuple hv_Sigma, HTuple hv_Threshold,
            HTuple hv_Transition, HTuple hv_Select, HTuple hv_ROIRows, HTuple hv_ROICols,
            HTuple hv_Direct, out HTuple hv_ResultRow, out HTuple hv_ResultColumn, out HTuple hv_ArcType)
        {
            throw new Exception();
        }



    }
}
